Test must now work

diff --git a/trunk/binaryTrees/C++/Makefile b/trunk/binaryTrees/C++/Makefile
--- a/trunk/binaryTrees/C++/Makefile
+++ b/trunk/binaryTrees/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./binarytrees $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> binaryTrees C++: OK",\
-	 	@echo ">> binaryTrees C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> binaryTrees C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=binarytrees-C++-time.csv \
@@ -23,5 +24,5 @@ build:
 	$(GPP) $(GPPOPTS) binarytrees.cpp -o binarytrees
 
 clean:
-	rm -fr *~ binarytrees $(FILE) *.csv
+	rm -fr *~ binarytrees $(FILE) *.csv *.diff
 
diff --git a/trunk/binaryTrees/vala/Makefile b/trunk/binaryTrees/vala/Makefile
--- a/trunk/binaryTrees/vala/Makefile
+++ b/trunk/binaryTrees/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./binarytrees $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> binaryTrees Vala: OK",\
-		@echo ">> binaryTrees Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> binaryTrees vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=binarytrees-vala-time.csv \
diff --git a/trunk/fannkuch/vala/Makefile b/trunk/fannkuch/vala/Makefile
--- a/trunk/fannkuch/vala/Makefile
+++ b/trunk/fannkuch/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./fannkuch $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fannkuch Vala: OK",\
-	 	@echo ">> fannkuch Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fannkuch vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fannkuch-vala-time.csv \
diff --git a/trunk/fasta/plain-C/Makefile b/trunk/fasta/plain-C/Makefile
--- a/trunk/fasta/plain-C/Makefile
+++ b/trunk/fasta/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./fasta $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fasta plain-C: OK",\
-	 	@echo ">> fasta plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fasta plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fasta-plain-C-time.csv \
diff --git a/trunk/mandelbrot/C++/Makefile b/trunk/mandelbrot/C++/Makefile
--- a/trunk/mandelbrot/C++/Makefile
+++ b/trunk/mandelbrot/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./mandelbrot $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> mandelbrot C++: OK",\
-	 	@echo ">> mandelbrot C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> mandelbrot C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=mandelbrot-C++-time.csv \
diff --git a/trunk/mandelbrot/mono/Makefile b/trunk/mandelbrot/mono/Makefile
--- a/trunk/mandelbrot/mono/Makefile
+++ b/trunk/mandelbrot/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) mandelbrot.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> mandelbrot mono: OK",\
-	 	@echo ">> mandelbrot mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> mandelbrot mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=mandelbrot-mono-time.csv \
diff --git a/trunk/mandelbrot/vala/Makefile b/trunk/mandelbrot/vala/Makefile
--- a/trunk/mandelbrot/vala/Makefile
+++ b/trunk/mandelbrot/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./mandelbrot $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> mandelbrot Vala: OK",\
-	 	@echo ">> mandelbrot Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> mandelbrot vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=mandelbrot-vala-time.csv \
diff --git a/trunk/nBody/C++/Makefile b/trunk/nBody/C++/Makefile
--- a/trunk/nBody/C++/Makefile
+++ b/trunk/nBody/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nbody $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nBody C++: OK",\
-	 	@echo ">> nBody C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nBody C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nbody-C++-time.csv \
diff --git a/trunk/nBody/mono/Makefile b/trunk/nBody/mono/Makefile
--- a/trunk/nBody/mono/Makefile
+++ b/trunk/nBody/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) nbody.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nBody mono: OK",\
-	 	@echo ">> nBody mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nBody mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nbody-mono-time.csv \
diff --git a/trunk/nBody/plain-C/Makefile b/trunk/nBody/plain-C/Makefile
--- a/trunk/nBody/plain-C/Makefile
+++ b/trunk/nBody/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nbody $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nBody plain-C: OK",\
-	 	@echo ">> nBody plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nBody plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nbody-plain-C-time.csv \
diff --git a/trunk/nBody/vala/Makefile b/trunk/nBody/vala/Makefile
--- a/trunk/nBody/vala/Makefile
+++ b/trunk/nBody/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nbody $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nBody Vala: OK",\
-		@echo ">> nBody Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nBody vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nbody-vala-time.csv \
diff --git a/trunk/nsieve/mono/Makefile b/trunk/nsieve/mono/Makefile
--- a/trunk/nsieve/mono/Makefile
+++ b/trunk/nsieve/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) nsieve.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieve mono: OK",\
-	 	@echo ">> nsieve mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieve mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsieve-mono-time.csv \
diff --git a/trunk/nsieve/plain-C/Makefile b/trunk/nsieve/plain-C/Makefile
--- a/trunk/nsieve/plain-C/Makefile
+++ b/trunk/nsieve/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nsieve $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieve plain-C: OK",\
-	 	@echo ">> nsieve plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieve plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsieve-plain-C-time.csv \
diff --git a/trunk/nsieve/vala/Makefile b/trunk/nsieve/vala/Makefile
--- a/trunk/nsieve/vala/Makefile
+++ b/trunk/nsieve/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nsieve $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieve Vala: OK",\
-	 	@echo ">> nsieve Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieve vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsieve-vala-time.csv \
diff --git a/trunk/nsieveBits/mono/Makefile b/trunk/nsieveBits/mono/Makefile
--- a/trunk/nsieveBits/mono/Makefile
+++ b/trunk/nsieveBits/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) nsievebits.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieveBits mono: OK",\
-	 	@echo ">> nsieveBits mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieveBits mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsievebits-mono-time.csv \
diff --git a/trunk/partialSums/plain-C/Makefile b/trunk/partialSums/plain-C/Makefile
--- a/trunk/partialSums/plain-C/Makefile
+++ b/trunk/partialSums/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./partialsums $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> partialSums plain-C: OK",\
-	 	@echo ">> partialSums plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> partialSums plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=partialSums-plain-C-time.csv \
diff --git a/trunk/recursive/C++/Makefile b/trunk/recursive/C++/Makefile
--- a/trunk/recursive/C++/Makefile
+++ b/trunk/recursive/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./recursive $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> recursive C++: OK",\
-	 	@echo ">> recursive C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> recursive C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=recursive-C++-time.csv \
diff --git a/trunk/recursive/mono/Makefile b/trunk/recursive/mono/Makefile
--- a/trunk/recursive/mono/Makefile
+++ b/trunk/recursive/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) recursive.exe $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> recursive mono: OK",\
-	 	@echo ">> recursive mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> recursive mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=recursive-mono-time.csv \
diff --git a/trunk/recursive/plain-C/Makefile b/trunk/recursive/plain-C/Makefile
--- a/trunk/recursive/plain-C/Makefile
+++ b/trunk/recursive/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./recursive $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> recursive plain-C: OK",\
-	 	@echo ">> recursive plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> recursive plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=recursive-plain-C-time.csv \
diff --git a/trunk/sumFile/C++/Makefile b/trunk/sumFile/C++/Makefile
--- a/trunk/sumFile/C++/Makefile
+++ b/trunk/sumFile/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./sumcol <../$(INTESTFILE) > $(OUTFILE)
-	$(if $(diff $(OUTFILE) ../$(OUTFILE)), @echo ">> sumFile C++: OK",\
-	 	@echo ">> sumFile C++: Failed")
+	@if ! cmp $(OUTFILE) ../$(OUTFILE); then \
+	echo ">> sumFile C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	gzip -dc ../$(GZINFILE) > ../$(INFILE)
diff --git a/trunk/sumFile/plain-C/Makefile b/trunk/sumFile/plain-C/Makefile
--- a/trunk/sumFile/plain-C/Makefile
+++ b/trunk/sumFile/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./sumcol <../$(INTESTFILE) > $(OUTFILE)
-	$(if $(diff $(OUTFILE) ../$(OUTFILE)), @echo ">> sumFile plain-C: OK",\
-	 	@echo ">> sumFile plain-C: Failed")
+	@if ! cmp $(OUTFILE) ../$(OUTFILE); then \
+	echo ">> sumFile plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	gzip -dc ../$(GZINFILE) > ../$(INFILE)
diff --git a/trunk/sumFile/vala/Makefile b/trunk/sumFile/vala/Makefile
--- a/trunk/sumFile/vala/Makefile
+++ b/trunk/sumFile/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./sumcol <../$(INTESTFILE) > $(OUTFILE)
-	$(if diff $(OUTFILE) ../$(OUTFILE), @echo ">> sumFile Vala: OK",\
-	 	@echo ">> sumFile Vala: Failed")
+	@if ! cmp $(OUTFILE) ../$(OUTFILE); then \
+	echo ">> sumFile vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	gzip -cd ../$(GZINFILE) > ../$(INFILE)
