Test must now work

diff --git a/binaryTrees/mono/Makefile b/binaryTrees/mono/Makefile
--- a/binaryTrees/mono/Makefile
+++ b/binaryTrees/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) binarytrees.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> binaryTrees mono: OK",\
-	 	@echo ">> binaryTrees mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> binaryTrees mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=binarytrees-mono-time.csv \
diff --git a/binaryTrees/plain-C/Makefile b/binaryTrees/plain-C/Makefile
--- a/binaryTrees/plain-C/Makefile
+++ b/binaryTrees/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./binarytrees $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> binaryTrees plain-C: OK",\
-	 	@echo ">> binaryTrees plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> binaryTrees plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=binarytrees-plain-C-time.csv \
diff --git a/fannkuch/C++/Makefile b/fannkuch/C++/Makefile
--- a/fannkuch/C++/Makefile
+++ b/fannkuch/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./fannkuch $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fannkuch C++: OK",\
-	 	@echo ">> fannkuch C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fannkuch C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fannkuch-C++-time.csv \
diff --git a/fannkuch/mono/Makefile b/fannkuch/mono/Makefile
--- a/fannkuch/mono/Makefile
+++ b/fannkuch/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) fannkuch.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fannkuch mono: OK",\
-	 	@echo ">> fannkuch mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fannkuch mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fannkuch-mono-time.csv \
diff --git a/fannkuch/plain-C/Makefile b/fannkuch/plain-C/Makefile
--- a/fannkuch/plain-C/Makefile
+++ b/fannkuch/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./fannkuch $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fannkuch plain-C: OK",\
-	 	@echo ">> fannkuch plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fannkuch plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fannkuch-plain-C-time.csv \
diff --git a/fasta/mono/Makefile b/fasta/mono/Makefile
--- a/fasta/mono/Makefile
+++ b/fasta/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) fasta.exe $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fasta mono: OK",\
-	 	@echo ">> fasta mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fasta mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fasta-mono-time.csv \
diff --git a/fasta/vala/Makefile b/fasta/vala/Makefile
--- a/fasta/vala/Makefile
+++ b/fasta/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./fasta $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> fasta Vala: OK",\
-	 	@echo ">> fasta Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> fasta vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=fasta-vala-time.csv \
diff --git a/mandelbrot/plain-C/Makefile b/mandelbrot/plain-C/Makefile
--- a/mandelbrot/plain-C/Makefile
+++ b/mandelbrot/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./mandelbrot $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> mandelbrot plain-C: OK",\
-	 	@echo ">> mandelbrot plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> mandelbrot plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=mandelbrot-plain-C-time.csv \
diff --git a/nsieve/C++/Makefile b/nsieve/C++/Makefile
--- a/nsieve/C++/Makefile
+++ b/nsieve/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nsieve $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieve C++: OK",\
-	 	@echo ">> nsieve C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieve C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsieve-C++-time.csv \
diff --git a/nsieveBits/plain-C/Makefile b/nsieveBits/plain-C/Makefile
--- a/nsieveBits/plain-C/Makefile
+++ b/nsieveBits/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nsievebits $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieveBits plain-C: OK",\
-	 	@echo ">> nsieveBits plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieveBits plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsievebits-plain-C-time.csv \
diff --git a/nsieveBits/vala/Makefile b/nsieveBits/vala/Makefile
--- a/nsieveBits/vala/Makefile
+++ b/nsieveBits/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./nsievebits $(NTEST) > $(FILE)
-	$(if $($(diff $(FILE) ../$(FILE))), @echo ">> nsieveBits Vala: OK",\
-	 	@echo ">> nsieveBits Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> nsieveBits vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=nsievebits-vala-time.csv \
diff --git a/partialSums/C++/Makefile b/partialSums/C++/Makefile
--- a/partialSums/C++/Makefile
+++ b/partialSums/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./partialsums $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> partialSums C++: OK",\
-	 	@echo ">> partialSums C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> partialSums C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=partialSums-C++-time.csv \
diff --git a/partialSums/mono/Makefile b/partialSums/mono/Makefile
--- a/partialSums/mono/Makefile
+++ b/partialSums/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) partialsums.exe $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> partialSums mono: OK",\
-	 	@echo ">> partialSums mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> partialSums mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=partialSums-mono-time.csv \
diff --git a/partialSums/vala/Makefile b/partialSums/vala/Makefile
--- a/partialSums/vala/Makefile
+++ b/partialSums/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./partialsums $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> partialSums Vala: OK",\
-	 	@echo ">> partialSums Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> partialSums vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=partialSums-vala-time.csv \
diff --git a/recursive/vala/Makefile b/recursive/vala/Makefile
--- a/recursive/vala/Makefile
+++ b/recursive/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./recursive $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> recursive Vala: OK",\
-	 	@echo ">> recursive Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> recursive vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=recursive-vala-time.csv \
diff --git a/spectralNorm/C++/Makefile b/spectralNorm/C++/Makefile
--- a/spectralNorm/C++/Makefile
+++ b/spectralNorm/C++/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./spectralnorm $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> spectralNorm C++: OK",\
-	 	@echo ">> spectralNorm C++: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> spectralNorm C++: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=spectralnorm-C++-time.csv \
diff --git a/spectralNorm/mono/Makefile b/spectralNorm/mono/Makefile
--- a/spectralNorm/mono/Makefile
+++ b/spectralNorm/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) spectralnorm.exe $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> spectralNorm mono: OK",\
-	 	@echo ">> spectralNorm mono: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> spectralNorm mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=spectralnorm-mono-time.csv \
diff --git a/spectralNorm/plain-C/Makefile b/spectralNorm/plain-C/Makefile
--- a/spectralNorm/plain-C/Makefile
+++ b/spectralNorm/plain-C/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./spectralnorm $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> spectralNorm plain-C: OK",\
-	 	@echo ">> spectralNorm plain-C: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> spectralNorm plain-C: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=spectralnorm-plain-C-time.csv \
diff --git a/spectralNorm/vala/Makefile b/spectralNorm/vala/Makefile
--- a/spectralNorm/vala/Makefile
+++ b/spectralNorm/vala/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	./spectralnorm $(NTEST) > $(FILE)
-	$(if $(diff $(FILE) ../$(FILE)), @echo ">> spectralNorm Vala: OK",\
-	 	@echo ">> spectralNorm Vala: Failed")
+	@if ! cmp $(FILE) ../$(FILE); then \
+	echo ">> spectralNorm vala: Failed"; exit 1; \
+	fi
 
 bench: build
 	$(TIME) --output=spectralnorm-vala-time.csv \
diff --git a/sumFile/mono/Makefile b/sumFile/mono/Makefile
--- a/sumFile/mono/Makefile
+++ b/sumFile/mono/Makefile
@@ -8,8 +8,9 @@ all: clean build test bench
 
 test: build
 	$(MONORUN) sumcol.exe <../$(INTESTFILE) > $(OUTFILE)
-	$(if $(diff $(OUTFILE) ../$(OUTFILE)), @echo ">> sumFile mono: OK",\
-	 	@echo ">> sumFile mono: Failed")
+	@if ! cmp $(OUTFILE) ../$(OUTFILE); then \
+	echo ">> sumFile mono: Failed"; exit 1; \
+	fi
 
 bench: build
 	gzip -dc ../$(GZINFILE) > ../$(INFILE) ;
